version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8027:8027"
    environment:
      - COMET_API_KEY=${COMET_API_KEY}
      - HG_TOKEN=${HG_TOKEN}
      - COMET_WORKSPACE=${COMET_WORKSPACE}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  bot:
    build: ./bot
    depends_on:
      - api
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - API_URL=http://api:8027
